### ISSUE TITLE
nav bar names

### ISSUE THREAD

**Issue by rimmesbe** [mrrichardasmith/f1-3-c2p1-colmar-academy#1]
I'd recommend giving these navs more descriptive class names so it's very obvious one is for mobile and one is for desktop. Even using the class names mobile and desktop might not be a bad idea or 
.nav-mobile, .nav-desktop
Just something so it's obvious one will be visible at a time.

https://github.com/mrrichardasmith/f1-3-c2p1-colmar-academy/blob/master/capstone_colmar_project/index.html#L17-L28

**Comment by mrrichardasmith** [comment]
Thanks again. Noted all your feedback in my summary notes.
