### ISSUE TITLE
button role button

### ISSUE THREAD

**Issue by rimmesbe** [mrrichardasmith/f1-3-c2p1-colmar-academy#2]
Probably don't need to clarify the button tags usage. I see this in some other places as well: h1 role=header, a role=link
You only need to declare the role if the tag is not acting in its intended nature or perhaps you are using a non-descriptive tag like div or span. 

https://github.com/mrrichardasmith/f1-3-c2p1-colmar-academy/blob/master/capstone_colmar_project/index.html#L40

**Comment by mrrichardasmith** [comment]
I will go back and re-read the documentation more completely. I pulled those suggestions out of the Aria docs to make sure that I had contributed something from each of the subjects covered for the mobile reader clients. It makes sense that links do not need to be clarified.
