### ISSUE TITLE
content div

### ISSUE THREAD

**Issue by rimmesbe** [mrrichardasmith/f1-3-c2p1-colmar-academy#3]
Usually the header and footer would not be included in a margining/centering content div like this. Headers usually take the full width. It looks pretty strange that the entire side has huge space on both side, looks like an image of a site. If you take the borders off the sides of the section you might be able to get away with it.

https://github.com/mrrichardasmith/f1-3-c2p1-colmar-academy/blob/master/capstone_colmar_project/index.html#L10

**Comment by mrrichardasmith** [comment]
This was me getting confused with the design picture. I got it into my head that this was a requirement. The feedback makes complete sense I will be less literal in future.
