### ISSUE TITLE
mobile content width

### ISSUE THREAD

**Issue by rimmesbe** [mrrichardasmith/f1-3-c2p1-colmar-academy#4]
I would definitely make this change to width: 100% on mobile, you really need to make the most use out of the limited space on a phone screen. 

https://github.com/mrrichardasmith/f1-3-c2p1-colmar-academy/blob/master/capstone_colmar_project/resources/css/style.css#L56-L57

**Comment by mrrichardasmith** [comment]
That makes sense. Will keep that in mind in the future.,
