### ISSUE TITLE
css naming convention

### ISSUE THREAD

**Issue by rimmesbe** [mrrichardasmith/f1-3-c2p1-colmar-academy#5]
Names like this really stick out: row1, row2, section1, section2
You want to think of css classes as modules or components that can be reused and moved around and are always the same, reliable. If you have to start numbering your classes that means you should just be creating separate components for those two things. row1 and row2 have the exact same styling, so they should just be row, both. I would take a look at BEM css naming convention: 
http://getbem.com/introduction/

**Comment by mrrichardasmith** [comment]
Will read this on the train today
