### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [mrrichardasmith/f1-3-c2p1-colmar-academy#6]
Grade: Satisfactory

Summary: Nice job on this project, The end result looks pretty good and your media queries are working nicely. You used a lot of good techniques and like the animations/transition. Take a look at issues I created as they will give you some tips on organizing your code a bit and taking it to that next level. Naming convention is a particularly important thing in css so it's worth adopting a well known convention like BEM or others that exist.
Good job on this final, hope you enjoyed the course.

**Comment by mrrichardasmith** [comment]
Thought the course was fantastic. Really helped build my confidence. I will look into BEM. 
I have just discovered that I might be losing my job to restructuring and hope to make this the opportunity to really up the intensity with my development skills. Next step more advanced Javascript.
